name: FFmpeg Windows Static Build with x265

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        shell: powershell
        run: |
          $env:Path += ";C:\ProgramData\chocolatey\bin"
          choco install -y git nasm yasm cmake mingw make

      - name: Check Git Availability
        shell: powershell
        run: |
          $env:Path += ";C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd"
          git --version

      - name: Build x265 (clone, cmake, make, install)
        shell: powershell
        run: |
          $env:Path += ";C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"
          git clone https://bitbucket.org/multicoreware/x265_git.git
          cd x265_git
          mkdir -Force build\msys
          cd build\msys
          cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=$(pwd)\install -DENABLE_SHARED=OFF ..\..\source
          $cpu = (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
          mingw32-make -j $cpu
          mingw32-make install

      - name: Build FFmpeg (clone, configure, make)
        shell: powershell
        run: |
          $env:Path += ";C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"
          git clone https://github.com/FFmpeg/FFmpeg.git
          cd FFmpeg
          .\configure --enable-gpl --enable-libx265 --enable-static --disable-shared --extra-cflags="-I..\x265_git\build\msys\install\include" --extra-ldflags="-L..\x265_git\build\msys\install\lib" --target-os=mingw32 --arch=x86_64 --disable-x86asm
          echo LastExitCode: $LASTEXITCODE
          if ($LASTEXITCODE -ne 0) {
            Write-Host '==== CONFIGURE ERROR (truncated log) ===='
            Get-Content config.log -ErrorAction SilentlyContinue | Select-Object -First 40
            exit $LASTEXITCODE
          }
          $cpu = (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
          mingw32-make -j $cpu

      - name: Prepare Release
        shell: powershell
        run: |
          $env:Path += ";C:\ProgramData\chocolatey\bin"
          mkdir release
          Copy-Item FFmpeg\ffmpeg.exe release\
          7z a ffmpeg-windows-x265.zip .\release\*

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "build-${{ github.run_number }}"
          files: |
            ffmpeg-windows-x265.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
